method: random
metric:
  name: val/val_avg_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: log_uniform
    min: 0.0001
    max: 0.1
  optimizer:
    value: "adam"
  loss_func:
    value: "mse"
  model_architecture:
    values: ["RESNET34", "RESNET50", "VGG19"]
  epochs:
    value: 150
  weight_decay:
    value: 0
  sigma:
    distribution: log_uniform
    min: 0.0001
    max: 0.1
  patience:
    value: 10
  lr_patience:
    value: 5
  dataset:
    parameters:
      name:
        value: "SpineDataset"
      batch_size:
        values: [2, 4]
      data_augmentation:
        value: True
      random:
        value: True
      split:
        value: 0.2
      split_wise:
        value: "Patient ID"