name: 

method: bayes

metric:
  name: val/val_avg_loss
  goal: minimize

parameters:
  
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  
  optimizer:
    value: "adam"
  
  loss_func:
    value: "heatmap_loss"
  
  model_architecture:
    parameters:
      model:
        values: ["UNET_SM","FPN_SM"]
      backbone: 
        values: [
                  'resnet50',
                  'densenet121', 
                  'efficientnet-b0',
                  'efficientnet-b4',
                  'efficientnet-b5',
                  'xception',
                  'dpn68'
                ]
      encoder_weights: 
        value: "imagenet"
      # decoder_use_batchnorm:
      #   value: True
      levels: 
        value: 5
  
  epochs:
    value: 150
  
  weight_decay:
    value: 0
  
  sigma:
    distribution: log_uniform_values
    min: 0.0005
    max: 0.1

  delta:
    value: 0.05
  
  patience:
    value: 10
  
  lr_patience:
    value: 5
  
  dataset:
    parameters:
      name:
        value: "SpineDataset"
      batch_size:
        values: [2, 4]
      data_augmentation:
        value: True
      random:
        value: True
      split:
        value: 0.2
      split_wise:
        value: "PatientID"
